name: Test

on:
  pull_request:
    types:
      - opened
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install package
        run: python setup.py install

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          pytest